name: CI
on:
  push:
    branches: [ "docking_inter" ]
  pull_request:
    branches: [ "docking_inter" ]
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        os: [macos-latest]
        include:
          # - os: windows-latest
          #   imgui-dir: lua-imgui-win64
          #- os: ubuntu-latest
           # imgui-dir: lua-imgui-ubuntu
          - os: macos-latest
            imgui-dir: lua-imgui-macos
        #os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set MACOSX_DEPLOYMENT_TARGET
        if: runner.os == 'macOS'
        run: |
          echo 'MACOSX_DEPLOYMENT_TARGET=14.0' >> $GITHUB_ENV
          
      # - name: Install libgl
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt update
      #     sudo apt install libgl-dev
          
      # - name: Build SDL2
      #   shell: bash
      #   run: |
      #     cd LuaJIT-SDL2/SDL &&
      #     cmake -Bbuild 
      #     cmake --build build --parallel $(nproc)
      # 
      # - name: Install SDL2
      #   if: matrix.os != 'windows-latest'
      #   shell: bash
      #   run: |
      #     cd LuaJIT-SDL2/SDL &&
      #     sudo cmake --build build --parallel $(nproc) --target install
      # 
      # - name: Install SDL2
      #   if: matrix.os == 'windows-latest'
      #   shell: bash
      #   run: |
      #     cd LuaJIT-SDL2/SDL &&
      #     cmake --build build --parallel $(nproc) --target install
          
      - name: Build and install LuaJIT-ImGui
        # if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          export BUILD_DIR='${{ github.workspace }}/${{ matrix.imgui-dir }}'
          export INSTALL_PREFIX=${{ github.workspace }}/${{ matrix.os }}_dir
          mkdir '${{ github.workspace }}/${{ matrix.imgui-dir }}'
          cmake -DCMAKE_BUILD_TYPE=Debug -DIMPL_GLFW=no -DIMPL_SDL=yes -DIMPL_OPENGL2=no -DIMPL_OPENGL3=yes -DSDL_PATH="" -DLUAJIT_BIN='${{ github.workspace }}/${{ matrix.imgui-dir }}' -Bbuild
          cmake --build build --parallel 16 --verbose
          cmake --build build -t install
          # echo "Will install to ${INSTALL_PREFIX}"
          # mkdir -p ${INSTALL_PREFIX}/share/lua/5.1/
          # mkdir -p ${INSTALL_PREFIX}/lib/lua/5.1/
          # mv ${BUILD_DIR}/lua/* ${INSTALL_PREFIX}/share/lua/5.1/
          # rm -r ${BUILD_DIR}/lua
          # mv ${BUILD_DIR}/* ${INSTALL_PREFIX}/lib/lua/5.1/

      - name: Compress install dir
        run: |
          tar -C ${{ github.workspace }}/${{ matrix.imgui-dir }} -czvf ${{ github.workspace }}/${{ matrix.imgui-dir }}.tar.gz .

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.imgui-dir }}.tar.gz
          path: ${{ github.workspace }}/${{ matrix.imgui-dir }}.tar.gz
